apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-pod
  labels:
    author: david
    type: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
      labels:
        type: webserver
    spec:
      containers:
        - name: httpd-pods
          image: httpd
          ports:
            - containerPort: 8080
              hostPort: 8080
...

