apiVersion: v1
kind: Pod
metadata:
  name: myhttpd
  labels:
    author: david
    type: webserver
spec:
  containers:
    - name: http
      image: httpd
      ports:
        - containerPort: 8080
          hostPort: 8080
      volumeMounts:
        - name: httpd
          mountPath: /home/tmmmmmm
  volumes:
    - name: httpd
      emptyDir:
        {}
...
