apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    author: david
    type: appserver
spec:
  containers:
    - name: tomcat2
      image: tomcat
      ports:
        - containerPort: 8080
          hostPort: 8080
      volumeMounts:
        - name: tomcat
          mountPath: /david/tomcat/
  volumes:
    - name: tomcat
      emptyDir: {}
