apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    author: david
    type: webserver
spec:
  containers:
    - name: myredis
      image: redis
      volumeMounts:
        - name: redis-volume
          mountPath: /data/myredis1
  volumes:
    - name: redis-volume
      emptyDir: {}

